### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ':'

### ISSUE THREAD

**Issue by jamila-griffith** [VasylVaskivskyi/biostitch#10]
Hi, 

I have installed this package in Anaconda and created a new environment. After running this code in the Terminal I am getting this error:
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ':'

Not sure what is causing this error. Just wondering if you can help.

Thanks

**Comment by jamila-griffith** [comment]
My code is working now. But the problem is that its producing only one well and not doing for all wells.

**Comment by VasylVaskivskyi** [comment]
Hi @jamila-griffith, please use BigStitcher or the stitcher provided by Perkin Elmer. 
The code in this repo was never made to the production quality and has problems with stithcing automatically acquired tiles.
