### ISSUE TITLE
AttributeError: 'list' object has no attribute 'iloc'

### ISSUE THREAD

**Issue by ibordeu** [VasylVaskivskyi/biostitch#8]
Hi, 
I am running 
$ python -m biostitch --img_dir "/Well_A3_channel_3_only/" --out_dir "/Well_A3_channel_3_only/biostitch_out/" --mode "stack" --scan "auto" --reference_channel "DAPI" --stitch_channels "DAPI"

In the "Well_A3_channel_3_only" folder I have the Index.idx.xml file and the individual tiles.

but I run into the following error:

started 2020-05-19 11:35:50.073766

processing channel no.1/1 DAPI
started at 2020-05-19 11:35:50.966332
plane 1/100Traceback (most recent call last):
  File "/Users/user_name/anaconda3/envs/biostitch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/user_name/anaconda3/envs/biostitch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/biostitch/__main__.py", line 64, in <module>
    main()
  File "/biostitch-master/biostitch/__main__.py", line 60, in main
    stitcher.stitch()
  File "/biostitch-master/biostitch/stitcher.py", line 61, in stitch
    self.perform_stitching(ids, x_size, y_size, plane_path_list, field_path_list, self._ome_meta)
  File "/biostitch-master/biostitch/stitcher.py", line 237, in perform_stitching
    TW.save(stitch_plane(plane, ids, x_size, y_size, self._y_pos, self._ill_cor_ch[channel], self._scan),
  File "/biostitch-master/biostitch/image_processing.py", line 185, in stitch_plane
    ncols = sum(x_size.iloc[0, :])
AttributeError: 'list' object has no attribute 'iloc'

Would you know why this is happening? 
Thanks!

**Comment by ibordeu** [comment]
Apparently it had to do with the scan method. I had --scan "auto" when it should have been --scan "manual". It is working now.

**Comment by VasylVaskivskyi** [comment]
Hi @ibordeu 

Thank you for reporting this bug. It should have worked regardless of `scan` mode. So I will have look at it. 
By the way, what scanning you used: **manual** where you manually select fields of view that will be imaged or **automatic** where microscope does it by itself?

**Comment by ibordeu** [comment]
Hi @VasylVaskivskyi ,
I checked with the experimentalists, they did a manual selection of the positions in each well in order to minimise the total size of the dataset.

Thanks for making your code available! It is very useful.

**Comment by VasylVaskivskyi** [comment]
Fixed
1727deaa5c155b09e4b394290fed688e235be908
